// React/tutorial/src/component/detalles-anime.js
import React, { useState } from "react";
import { useEffect } from "react";
import "./detalles-anime.css";
import {
    BrowserRouter as Router,
    Routes,
    Route,
    Link,
    useParams
} from 'react-router-dom';


function DetallesAnime() {
    const { id } = useParams();
    const [entrada, setEntrada] = useState();
    const [episodios, setEpisodios] = useState();
    const [dataIsLoaded, setDataIsLoaded] = useState(false);
    const [episodedDataIsLoaded, setEpisodeDataIsLoaded] = useState(false);


    useEffect(() => {
        if (!entrada) {
            recuperarDetalles();
            console.log('useEffect detalles');


        }
        if (!episodios) {
            recuperarEpisodios();
            console.log('useEffect episodios');

        }

    }, []);

    function recuperarDetalles() {
        fetch(
            "https://api.jikan.moe/v4/anime/" + id)
            .then((res) => res.json())
            .then((json) => {
                setEntrada(json);
                setDataIsLoaded(true);
            }).catch();
    }

    function recuperarEpisodios() {
        fetch(('https://api.jikan.moe/v4/anime/' + id + '/episodes'))
            .then((res) => res.json())
            .then((json) => {
                setEpisodios(json);
                setEpisodeDataIsLoaded(true);
            }).catch();
    }
    //('https://api.jikan.moe/v4/anime/' + id)




    if (!dataIsLoaded || !episodedDataIsLoaded) return <div>
        <h1> Pleses wait some time.... </h1> </div>;
        
    return (
        <div className="grid-container">
            <div className="item1">
                <img src={entrada.data.images.jpg.large_image_url} alt="hola" />
                <h3>{entrada.data.title}</h3>

                <h4>Títulos alternativos <hr /> </h4>
                <p>Título original: {entrada.data.title} ({entrada.data.title_japanese})  </p>
                <p>Título en inglés: {entrada.data.title_english}</p>
                <h4>Información <hr /></h4>
                <p>Tipo: {entrada.data.type}</p>
                <p>Fuente: {entrada.data.source}</p>
                <p>Número de episodios: {entrada.data.episodes}</p>
                <p>Fecha de emisión: {entrada.data.aired.string}</p>
                <p>Puntuación: {entrada.data.score}</p>
                <p>Temporada: {entrada.data.season} {entrada.data.year}</p>
                <p>Género:     </p >
            </div >
            <div className="item2">
                <h2>Sinopsis<hr /></h2>
                <p>{entrada.data.synopsis}</p>
            </div>
            <div className="item3">            
                <table>
                    <thead>
                        <tr>
                            <th>Número</th>
                            <th>Título</th>
                            <th>Fecha de emisión</th>
                        </tr>
                    </thead>
                    <tbody>
                        {episodios.data.map((episodio) => (
                            <tr key={episodio.mal_id}>
                                <td>{episodio.mal_id}</td>
                                <td>{episodio.title}</td>
                                <td>{episodio.aired.slice(0, 10)}</td>
                            </tr>
                        ))}
                    </tbody>

                </table>
            </div >
        </div >
    );
}

export default DetallesAnime;

// Angular/src/app/detalles-anime/detalles-anime.component.ts
import { EntradaService } from './../shared/services/entrada.service';
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FirestoreManagerService } from '../shared/services/firestore-manager.service';
import { AuthService } from '../shared/services/auth.service';
import { map } from 'rxjs';

@Component({
  selector: 'app-detalles-anime',
  templateUrl: './detalles-anime.component.html',
  styleUrls: ['./detalles-anime.component.scss']
})
export class DetallesAnimeComponent implements OnInit {
  public entrada: any;
  public animeid: string = "";
  public listaEpisodios: any;
  public esFavorito?: boolean = false;
  public estaLogeado?: boolean;
  constructor(private entradaService: EntradaService, private router: Router,
    private route: ActivatedRoute, private db: FirestoreManagerService,
    public login: AuthService) {
      this.route.queryParams.subscribe(params => {
        this.animeid = params['animeid'];
      });

      if(this.login.isLoggedIn)
      {
        this.recuperarFavoritos()
        console.log('fav ejecutado')
      }


    this.recuperarEntrada();
    this.recuperarCapitulos();
    console.log('variable en on init')
    console.log(this.esFavorito)
    }

  ngOnInit(): void {

  }

  public recuperarCapitulos(): void {
    this.entradaService.recuperarEpisodiosPorId(this.animeid).subscribe(
      (data) => {
        this.listaEpisodios = data;
      },
      (error) => {

      },
      () => {

      }
    )
  }

  public recuperarEntrada(): void {
    this.entradaService.recuperarEntradaPorId(this.animeid).subscribe(
      (data) => {
        this.entrada = data;
      },
      (error) => {

      },
      () => {

      }
    )
  }

  public recuperarEntradasPopularidad(): void {
    this.entradaService.recuperarEntradasPopularidad().subscribe(
      (data) => {
        this.entrada = data;
      },
      (error) => {

      },
      () => {

      }
    );
  }

  guardarAnime(animeid: string): void {
    this.db.create(animeid).then(() => {
      console.log('Created new item successfully!');
      this.esFavorito = true;
    });
  }

   borrarFavorito(animeid: string):void {
    this.db.delete(animeid + '').then(() => {
      console.log('Deleted item successfully!');
      this.esFavorito = false;
    });
  }

  isFav(animeid: string): boolean {
    let encontrado = false;
    let listaFavoritos = this.recuperarFavoritos();
    console.log(listaFavoritos)

    return encontrado;
  }

  recuperarFavoritos(): void {
    let encontrado = false;
    this.db.getAll().snapshotChanges().pipe(
      map(changes =>
        changes.map(c =>
          ({ key: c.payload.key, ...c.payload.val() })
        )
      )
    ).subscribe(data => {
      data.forEach((element: any) => {
        console.log('Clave' + element.key)
        console.log('Clave introducida: '+  this.animeid)
        if(element.key == this.animeid)
          {
            this.esFavorito = true;
          }
      });
    });

  }

}

<div class="grid-container">
  <div class="item1">
    <img src="{{entrada.data.images.jpg.large_image_url}}">
    <h3>{{entrada.data.title}}</h3>
    <p *ngIf="login.isLoggedIn">
      <button *ngIf="esFavorito == false" (click)="guardarAnime(animeid)" class="btn btn-primary my-2">Guardar en favoritos</button>
      <button *ngIf="esFavorito == true" (click)="borrarFavorito(animeid)" class="btn btn-secondary my-2">Borrar de favoritos</button>
    </p>
    <h4>Títulos alternativos <hr></h4>
    <p>Título original: {{entrada.data.title}} ({{entrada.data.title_japanese}})</p>
    <p>Título en inglés: {{entrada.data.title_english}}</p>
    <h4>Información<hr></h4>
    <p>Tipo: {{entrada.data.type}}</p>
    <p>Fuente: {{entrada.data.source}}</p>
    <p>Número de episodios: {{entrada.data.episodes}}</p>
    <p>Fecha de emisión: {{entrada.data.aired.string}}</p>
    <p>Puntuación: {{entrada.data.score}}</p>
    <p>Temporada: {{entrada.data.season}} {{entrada.data.year}}</p>
    <p>Estudio de animación: {{entrada.data.studios[0].name}}</p>
    <p>Género: <span *ngFor="let genero of entrada.data.genres">{{genero.name}}<span *ngIf="genero != entrada.data.genres[entrada.data.genres.length - 1]">, </span>
    </span>
    </p>
  </div>
  <div class="item2">
    <h2>Sinopsis<hr></h2>
    <p>{{entrada.data.synopsis}}</p>
  </div>
  <div class="item3">
    <h2>Lista de episodios<hr></h2>
    <table>
      <tr>
        <th>Número</th>
        <th>Título</th>
        <th>Fecha de emisión</th>
      </tr>
      <tr *ngFor="let episodio of listaEpisodios.data">
        <td>{{episodio.mal_id}}</td>
        <td>{{episodio.title}}</td>
        <td>{{episodio.aired.slice(0, 10)}}</td>
      </tr>
    </table>
  </div>
</div>
