// Angular/04_servicios/src/app/detalles-anime/detalles-anime.component.ts
import { EntradaService } from './../shared/services/entrada.service';
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'app-detalles-anime',
  templateUrl: './detalles-anime.component.html',
  styleUrls: ['./detalles-anime.component.css']
})
export class DetallesAnimeComponent implements OnInit {
  public entrada: any;
  public animeid: string = "";
  constructor(private entradaService: EntradaService, private router: Router, private route: ActivatedRoute) { }

  ngOnInit(): void {
    this.route.queryParams.subscribe(params => {
      this.animeid = params['animeid'];
    });
    this.recuperarEntrada();
  }

  public recuperarEntrada(): void {
    this.entradaService.recuperarEntradaPorId(this.animeid).subscribe(
      (data) => {
        this.entrada = data.data;
      },
      (error) => {

      },
      () => {

      }
    )
  }

  public recuperarEntradasPopularidad(): void {
    this.entradaService.recuperarEntradasPopularidad().subscribe(
      (data) => {
        this.entrada = data;
      },
      (error) => {

      },
      () => {

      }
    );
  }

  public test():void {
    console.log();
  }

}

<div class="grid-container">
  <div class="item1">
    <img (click)="test()" src="{{entrada.images.jpg.large_image_url}}">
    <h3>{{entrada.title}}</h3>
    <h4>Títulos alternativos <hr></h4>
    <p>Título original: {{entrada.title}} ({{entrada.title_japanese}})</p>
    <p>Título en inglés: {{entrada.title_english}}</p>

  </div>
  <div class="item2">
    <h2>Sinopsis<hr></h2>
    <p>{{entrada.synopsis}}</p>
  </div>
  <div class="item3">
    <h4>Información<hr></h4>
    <p>Tipo: {{entrada.type}}</p>
    <p>Fuente: {{entrada.source}}</p>
    <p>Número de episodios: {{entrada.episodes}}</p>
    <p>Fecha de emisión: {{entrada.aired.string}}</p>
    <p>Puntuación: {{entrada.score}}</p>
    <p>Temporada: {{entrada.season}} {{entrada.year}}</p>
    <p>Estudio de animación: {{entrada.studios[0].name}}</p>
  </div>

</div>

// React/tutorial/src/component/detalles-anime.js
import React, { useState } from "react";
import { useEffect } from "react";
import "./detalles-anime.css";
import {
    BrowserRouter as Router,
    Routes,
    Route,
    Link,
    useParams
} from 'react-router-dom';


function DetallesAnime() {
    const { id } = useParams();
    const [entrada, setEntrada] = useState();
    const [episodios, setEpisodios] = useState();


    useEffect(() => {
        // Actualiza el título del documento usando la API del navegador
        fetch(
            "https://api.jikan.moe/v4/anime/" + id)
            .then((res) => res.json())
            .then((json) => {
                setEntrada(json);
            })
        fetch(('https://api.jikan.moe/v4/anime/' + id +'/episodes'))
        .then((res) => res.json())
        .then((json) => {
            setEpisodios(json);
        })
    });    
    //('https://api.jikan.moe/v4/anime/' + id)




    if (!entrada || !episodios) return <div>
    <h1> Pleses wait some time.... </h1> </div>;

    return (
        <div className="grid-container">
            <div className="item1">
                <img src={entrada.data.images.jpg.large_image_url} />
                <h3>{entrada.data.title}</h3>

                <h4>Títulos alternativos <hr/> </h4>
                <p>Título original: {entrada.data.title} ({entrada.data.title_japanese})  </p>
                <p>Título en inglés: {entrada.data.title_english}</p>
                <h4>Información <hr/></h4>
                <p>Tipo: {entrada.data.type}</p>
                <p>Fuente: {entrada.data.source}</p>
                <p>Número de episodios: {entrada.data.episodes}</p>
                <p>Fecha de emisión: {entrada.data.aired.string}</p>
                <p>Puntuación: {entrada.data.score}</p>
                <p>Temporada: {entrada.data.season} {entrada.data.year}</p>
                <p>Estudio de animación: {entrada.data.studios[0].name}</p>
                <p>Género:     </p >
            </div >
            <div className="item2">
                <h2>Sinopsis<hr /></h2>
                <p>{entrada.data.synopsis}</p>
            </div>
            <div className="item3">
                <h2>Lista de episodios<hr /></h2>
                <table>
                    <tr>
                        <th>Número</th>
                        <th>Título</th>
                        <th>Fecha de emisión</th>
                    </tr>
                    <tr >
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                </table>
            </div >
        </div >
    );
}

export default DetallesAnime;
